name: test

# Run this workflow every time a new commit pushed to your repository
on: ['push', 'pull_request']

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test:
    # Name the Job
    name: Test
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 17.x, 18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Npm install
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: github.ref == 'refs/heads/master'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
